spring:
  application:
    name: api-gateway

server:
  port: 8080
  # address : localhost
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring.cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOriginPatterns: "*"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"
      #       allowCredentials: true
      routes:
        - id: studentservice
          uri: lb://studentservice
          predicates:
            - Path=/studentservice/api/**
          filters:
            - JwtAuthFilter

        - id: masterservice
          uri: lb://masterservice
          predicates:
            - Path=/masterservice/api/**
          filters:
            - JwtAuthFilter


        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/authservice/api/**
          filters:
            - JwtAuthFilter
            
        - id: notificationservice
          uri: lb://notificationservice
          predicates:
            - Path=/notificationservice/api/**


debug: true