spring:
  application:
    name: eureka-server

server:
  port: 8761
  address: 192.168.1.90

eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.90:8761/eureka
  server:
    enable-self-preservation: false

